# Question 1: Find the mean, median for Sachin, Rahul, India

In [1]:
import numpy as np

In [4]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)
cric_data.shape

(225, 4)

In [5]:
cric_data = cric_data[:, [1, 2, 3]]

In [6]:
cric_data.shape

(225, 3)

In [7]:
sachin = cric_data[:, 0]
rahul = cric_data[:, 1]
india = cric_data[:, 2]

In [8]:
sachin.shape

(225,)

In [9]:
def stats(col):
  print('Mean', np.mean(col))
  print('Median', np.median(col))

In [10]:
stats(sachin)

Mean 39.87555555555556
Median 27.0


In [11]:
stats(rahul)

Mean 32.062222222222225
Median 22.0


In [12]:
stats(india)

Mean 220.79555555555555
Median 216.0


In [13]:
np.mean(cric_data, axis=0)

array([ 39.87555556,  32.06222222, 220.79555556])

# Question 2: Find histogram of Sachin's scores with 10 bins

In [14]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

# Question 3: find mean of sachin's scores grouped by 25 matches

In [15]:
sachin.shape

(225,)

In [16]:
sachin25 = sachin.reshape(9, 25)

In [17]:
sachin25.shape

(9, 25)

In [18]:
np.mean(sachin25, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

# Question 4: Find mean of Sachin's scores where he has scored a century

In [19]:
sachin >= 100

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [20]:
sachin[sachin >= 100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])